#!/bin/bash

#
# ==== Set up workspace ====
#    ----- Nop much ----    
#
# FILES
#
# /etc/xdg/picom.conf
# /srv/wallpapers
# .bash_aliases
# .vimrc
# .config/
#	i3
#		config
#	polybar
#		backup_config
#		config
#	ranger
#		commands.py
#		commands_full.py
#		rc.conf
#		rifle.conf
#		scope.sh
# ~/bin
#	polybarstart
#	aS

# Check whether files are reachable
if [[ ! -f setup ]]; then
	echo "Please, run this script from the folder containing it."
	exit
fi

# Check wheather software requirements are met
while read packet; do
	if [[ ! -z "$(pacman -Q $packet | grep error)" ]]; then
		echo "Missing packet... $packet"
	fi	
done < paket_list.txt

mv config/* ~/.
mv .* ~/
