#!/bin/bash

# ==== Set up workspace ====
#    ----- Nop much ----    

# Check whether files are reachable
if [[ ! -f setup ]]; then
	echo "Please, run this script from the folder containing it."
	exit
fi

# Check wheather software requirements are met
echo 
echo Some work...
MISSING=false
while read package; do
	if [[ 0 -eq "$(pacman -Q $package | grep error | wc -l)" ]]; then
		echo "[!] $package ...Give it a shot!"
		MISSING=true
	fi	
done < package_list.txt 2>/dev/null
if ( $MISSING ); then 
	echo 
	echo "Missing some packages..."
	echo "Install them by pipeing the command into: awk '/[!] / {print $22}' | xargs sudo pacman -S"
	exit
fi

# Deploy

# Level ~
find -name '.*[^.git]' | xargs -I NAME ln -s $(pwd)/NAME $HOME/
# Level ~/bin 
ls bin | xargs -I NAME ln -s $(pwd)/bin/NAME $HOME/bin/
# Level ~/config
ls config | xargs -I NAME ln -s $(pwd)/config/NAME $HOME/.config/
