#!/bin/bash

#
# ==== Set up workspace ====
#    ----- Nop much ----    
#
# FILES
#
# /etc/xdg/picom.conf
# /srv/wallpapers
# .bash_aliases
# .vimrc
# .config/
#	i3
#		config
#	polybar
#		backup_config
#		config
#	ranger
#		commands.py
#		commands_full.py
#		rc.conf
#		rifle.conf
#		scope.sh
# ~/bin
#	polybarstart
#	aS

# Check whether files are reachable
if [[ ! -f setup ]]; then
	echo "Please, run this script from the folder containing it."
	exit
fi

# Check wheather software requirements are met
MISSING=false
while read package; do
	if [[ ! -z "$(pacman -Q $package | grep error)" ]]; then
		echo "Should have... $package"
		MISSING=true
	fi	
done < package_list.txt
if ( $MISSING ); then exit; fi

ln -s $(pwd)/config/i3 $HOME/.config/i3
ln -s $(pwd)/config/ranger $HOME/.config/ranger
ln -s $(pwd)/config/polybar $HOME/.config/polybar
ln -s $(pwd)/bin $HOME/bin
